from rsf.proj import *

## Velocity model
Flow('Fvel.rsf', None, 'sfspike mag=400,800 nsp=2 k1=1,201 l1=200,400 d1=0.05 d2=0.05 \
label1=z label2=x n1=400 n2=5000 o1=1 o2=1 unit1=m unit2=m')

## Density model
Flow('Fden.rsf', None, 'sfspike mag=1 nsp=1 k1=1 l1=400 d1=0.05 d2=0.05 \
label1=z label2=x n1=400 n2=5000 o1=1 o2=1 unit1=m unit2=m')

## Source position (x,z)
Flow('Fsou.rsf', None, 'sfspike n1=2 nsp=2 k1=1,2 mag=100,10 o1=0 o2=0')

## Receiver position (x,z)
Flow('Frec.rsf', None, 'sfspike n1=2 nsp=2 k1=1,2 mag=100,10 o1=0 o2=0')

## Source wavelet
Flow('Fwav.rsf', None, 'sfspike nsp=1 n1=10000 d1=0.000025 k1=200 | sfricker1 frequency=150 | sftransp')

End()
